# This file was generated by the deal.II library.
# Date =  2026/9/18
# Time =  10:29:53
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <spcrust> <spharz> <opcrust> <opharz> <density> <thermal_expansivity> <specific_heat> <viscosity> <current_cohesions> <current_friction_angles> <plastic_yielding> <dislocation_viscosity> <diffusion_viscosity> <peierls_viscosity> <nonadiabatic_pressure> <strain_rate> <stress> <stress> <stress> <stress> <adiabatic_heating> <latent_heat> <shear_heating> 
0 0 0 0 1.0662e+11 3210.6 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 -0 0 0 
4.448e+06 0 0 0 1.0662e+11 3210.6 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 -0 0 0 

0 2.89e+06 0 0 0 273 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 0 0 0 
4.448e+06 2.89e+06 0 0 0 273 0 0 1 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 0 0 0 


4.448e+06 0 0 0 1.0662e+11 3210.6 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 -0 0 0 
8.896e+06 0 0 0 1.0662e+11 3210.6 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 -0 0 0 

4.448e+06 2.89e+06 0 0 0 273 0 0 1 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 0 0 0 
8.896e+06 2.89e+06 0 0 0 273 0 0 0 0 3468.16 3.1e-05 1250 3.79851e+20 5e+07 25 0 nan nan nan 0 0 5.331e+10 0 0 5.331e+10 0 0 0 


