# This file was generated by the deal.II library.
# Date =  2026/9/19
# Time =  11:54:55
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <spcrust> <spharz> <opcrust> <opharz> <density> <thermal_expansivity> <specific_heat> <viscosity> <current_cohesions> <current_friction_angles> <current_yield_stresses> <plastic_yielding> <nonadiabatic_pressure> <strain_rate> <stress> <stress> <stress> <stress> <adiabatic_heating> <latent_heat> <shear_heating> 
0 0 0 0 1.10196e+11 3210.6 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 3e+08 0 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 
4.448e+06 0 0 0 1.10196e+11 3210.6 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 3e+08 0 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 

0 2.89e+06 0 0 0 273 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 4.53154e+07 1 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 
4.448e+06 2.89e+06 0 0 0 273 0 0 1 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 4.53154e+07 1 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 


4.448e+06 0 0 0 1.10196e+11 3210.6 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 3e+08 0 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 
8.896e+06 0 0 0 1.10196e+11 3210.6 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 3e+08 0 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 

4.448e+06 2.89e+06 0 0 0 273 0 0 1 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 4.53154e+07 1 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 
8.896e+06 2.89e+06 0 0 0 273 0 0 0 0 3570.08 3.1e-05 1250 9.61243e+21 5e+07 25 4.53154e+07 1 0 0 5.50982e+10 0 0 5.50982e+10 0 nan 0 


